INSERT INTO product (productName, crationDate, price) VALUES ('PANASONIC', NOW(), 809);
INSERT INTO product (productName, crationDate, price) VALUES ('SONY', NOW(), 1109.21);
INSERT INTO product (productName, crationDate, price) VALUES ('APPLE', NOW(), 2012);
INSERT INTO product (productName, crationDate, price) VALUES ('SANSUNG', NOW(), 999);
INSERT INTO product (productName, crationDate, price) VALUES ('HP', NOW(), 709.01);
INSERT INTO product (productName, crationDate, price) VALUES ('DELL', NOW(), 899);
INSERT INTO product (productName, crationDate, price) VALUES ('LENOVO', NOW(), 820);
INSERT INTO product (productName, crationDate, price) VALUES ('ASUS', NOW(), 702);
INSERT INTO product (productName, crationDate, price) VALUES ('IBM', NOW(), 834);